spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k8a707.p.ssafy.io:3306/luckquiz?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: eodrms
    password: eodrms

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  cloud:
    gcp:
      storage:
        bucket: luckquiz
        project-id: snappy-analog-384101
        credentials:
          location: classpath:snappy-analog-384101-5ff843401827.json

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true